## Spark

In [4]:
from pyspark.sql import SparkSession # type: ignore

# Initialize SparkSession
spark = SparkSession.builder \
    .appName("SimpleSparkApp") \
    .getOrCreate()

data = [("Alice", 34), ("Bob", 45), ("Cathy", 29)]
columns = ["Name", "Age"]

df = spark.createDataFrame(data, columns)

print("Original DataFrame:")
df.show()

df_filtered = df.filter(df.Age > 30)

print("Filtered DataFrame (Age > 30):")
df_filtered.show()

# Stop the SparkSession
spark.stop()

Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
24/12/19 10:25:50 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable


Original DataFrame:


+-----+---+
| Name|Age|
+-----+---+
|Alice| 34|
|  Bob| 45|
|Cathy| 29|
+-----+---+

Filtered DataFrame (Age > 30):
+-----+---+
| Name|Age|
+-----+---+
|Alice| 34|
|  Bob| 45|
+-----+---+



## RNN

In [5]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import SimpleRNN, Dense, Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import to_categorical

np.random.seed(42)
tf.random.set_seed(42)

# Generate synthetic data
num_samples = 1000
max_sequence_length = 10
vocab_size = 50
num_classes = 2

X = np.random.randint(1, vocab_size, size=(num_samples, max_sequence_length))
y = np.random.randint(0, num_classes, size=(num_samples,))

# Print synthetic data
print("Sample sequences (X):")
print(X[:5]) 

print("\nSample labels (y):")
print(y[:5]) 

# Pad sequences to ensure consistent input length
X_padded = pad_sequences(X, maxlen=max_sequence_length)

# One-hot encode the labels
y_encoded = to_categorical(y, num_classes=num_classes)

# Build the RNN model
model = Sequential()
model.add(Embedding(input_dim=vocab_size, output_dim=32, input_length=max_sequence_length))
model.add(SimpleRNN(units=64, return_sequences=False))
model.add(Dense(num_classes, activation='softmax'))

# Compile the model
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# Train the model
model.fit(X_padded, y_encoded, epochs=5, batch_size=32, validation_split=0.2)

# Evaluate the model
loss, accuracy = model.evaluate(X_padded, y_encoded)
print(f'Loss: {loss:.4f}, Accuracy: {accuracy:.4f}')


Sample sequences (X):
[[39 29 15 43  8 21 39 19 23 11]
 [11 24 36 40 24  3 22  2 24 44]
 [30 38  2 21 33 12 22 44 25 49]
 [27 42 28 16 15 47 44  3 37  7]
 [21  9 39 18  4 25 14  9 26  2]]

Sample labels (y):
[0 1 0 1 0]
Epoch 1/5


/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.4865 - loss: 0.6990 - val_accuracy: 0.4750 - val_loss: 0.7103
Epoch 2/5
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6594 - loss: 0.6553 - val_accuracy: 0.4850 - val_loss: 0.7317
Epoch 3/5
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6522 - loss: 0.6228 - val_accuracy: 0.4850 - val_loss: 0.7721
Epoch 4/5
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6642 - loss: 0.5939 - val_accuracy: 0.5050 - val_loss: 0.8152
Epoch 5/5
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6963 - loss: 0.5661 - val_accuracy: 0.5200 - val_loss: 0.8590
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 575us/step - accuracy: 0.7134 - loss: 0.5450
Loss: 0.5903, Accuracy: 0.6970


## LSTM

In [6]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import to_categorical

np.random.seed(42)
tf.random.set_seed(42)

# Generate synthetic data
num_samples = 1000
max_sequence_length = 10
vocab_size = 50
num_classes = 2

X = np.random.randint(1, vocab_size, size=(num_samples, max_sequence_length))
y = np.random.randint(0, num_classes, size=(num_samples,))

# Print synthetic data
print("Sample sequences (X):")
print(X[:5]) 

print("\nSample labels (y):")
print(y[:5])  

# Pad sequences to ensure consistent input length
X_padded = pad_sequences(X, maxlen=max_sequence_length)

# One-hot encode the labels
y_encoded = to_categorical(y, num_classes=num_classes)

# Build the LSTM model
model = Sequential()
model.add(Embedding(input_dim=vocab_size, output_dim=32, input_length=max_sequence_length))
model.add(LSTM(units=64, return_sequences=False))
model.add(Dense(num_classes, activation='softmax'))

# Compile the model
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# Train the model
model.fit(X_padded, y_encoded, epochs=5, batch_size=32, validation_split=0.2)

# Evaluate the model
loss, accuracy = model.evaluate(X_padded, y_encoded)
print(f'Loss: {loss:.4f}, Accuracy: {accuracy:.4f}')

Sample sequences (X):
[[39 29 15 43  8 21 39 19 23 11]
 [11 24 36 40 24  3 22  2 24 44]
 [30 38  2 21 33 12 22 44 25 49]
 [27 42 28 16 15 47 44  3 37  7]
 [21  9 39 18  4 25 14  9 26  2]]

Sample labels (y):
[0 1 0 1 0]
Epoch 1/5
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.4867 - loss: 0.6936 - val_accuracy: 0.4500 - val_loss: 0.6983
Epoch 2/5
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.5310 - loss: 0.6901 - val_accuracy: 0.4500 - val_loss: 0.6986
Epoch 3/5
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5312 - loss: 0.6882 - val_accuracy: 0.4450 - val_loss: 0.7001
Epoch 4/5
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5669 - loss: 0.6835 - val_accuracy: 0.4300 - val_loss: 0.7084
Epoch 5/5
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6147 - loss: 0.6705 - val_accuracy: 0.4150 - val_loss: 0.7623
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 793us/step - accuracy: 0.6245 - loss: 0.6461
Loss: 0.6688, Accuracy: 0.5800


## LORA

In [7]:
from transformers import DistilBertForSequenceClassification

model = DistilBertForSequenceClassification.from_pretrained('distilbert-base-uncased')
print(model)


Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


DistilBertForSequenceClassification(
  (distilbert): DistilBertModel(
    (embeddings): Embeddings(
      (word_embeddings): Embedding(30522, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (transformer): Transformer(
      (layer): ModuleList(
        (0-5): 6 x TransformerBlock(
          (attention): MultiHeadSelfAttention(
            (dropout): Dropout(p=0.1, inplace=False)
            (q_lin): Linear(in_features=768, out_features=768, bias=True)
            (k_lin): Linear(in_features=768, out_features=768, bias=True)
            (v_lin): Linear(in_features=768, out_features=768, bias=True)
            (out_lin): Linear(in_features=768, out_features=768, bias=True)
          )
          (sa_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
          (ffn): FFN(
            (dropout): Dropout(p=0.1, inplace=False)
 

In [8]:
from transformers import DistilBertForSequenceClassification

# Initialize the model
model = DistilBertForSequenceClassification.from_pretrained('distilbert-base-uncased')

# Function to print module names
def print_module_names(module, parent_name=''):
    for name, child in module.named_children():
        full_name = f"{parent_name}.{name}" if parent_name else name
        print(full_name)
        print_module_names(child, full_name)

print_module_names(model)


Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


distilbert
distilbert.embeddings
distilbert.embeddings.word_embeddings
distilbert.embeddings.position_embeddings
distilbert.embeddings.LayerNorm
distilbert.embeddings.dropout
distilbert.transformer
distilbert.transformer.layer
distilbert.transformer.layer.0
distilbert.transformer.layer.0.attention
distilbert.transformer.layer.0.attention.dropout
distilbert.transformer.layer.0.attention.q_lin
distilbert.transformer.layer.0.attention.k_lin
distilbert.transformer.layer.0.attention.v_lin
distilbert.transformer.layer.0.attention.out_lin
distilbert.transformer.layer.0.sa_layer_norm
distilbert.transformer.layer.0.ffn
distilbert.transformer.layer.0.ffn.dropout
distilbert.transformer.layer.0.ffn.lin1
distilbert.transformer.layer.0.ffn.lin2
distilbert.transformer.layer.0.ffn.activation
distilbert.transformer.layer.0.output_layer_norm
distilbert.transformer.layer.1
distilbert.transformer.layer.1.attention
distilbert.transformer.layer.1.attention.dropout
distilbert.transformer.layer.1.attention.q_

In [9]:
from transformers import DistilBertTokenizer, DistilBertForSequenceClassification, Trainer, TrainingArguments
from datasets import load_dataset
from peft import get_peft_model, LoraConfig

# Load and preprocess the dataset
dataset = load_dataset('glue', 'mrpc')
tokenizer = DistilBertTokenizer.from_pretrained('distilbert-base-uncased')

def preprocess_function(examples):
    return tokenizer(examples['sentence1'], examples['sentence2'], truncation=True, padding='max_length')

tokenized_datasets = dataset.map(preprocess_function, batched=True)

# Initialize model
model = DistilBertForSequenceClassification.from_pretrained('distilbert-base-uncased', num_labels=2)

# Set up LoRA configuration with corrected target modules
lora_config = LoraConfig(
    r=8,
    lora_alpha=32,
    lora_dropout=0.1,
    target_modules=[
        "distilbert.transformer.layer.*.attention.q_lin",
        "distilbert.transformer.layer.*.attention.k_lin",
        "distilbert.transformer.layer.*.attention.v_lin",
        "distilbert.transformer.layer.*.attention.out_lin",
    ],
)

# Get the LoRA model
model = get_peft_model(model, lora_config)

# Define training arguments
training_args = TrainingArguments(
    output_dir='./results',
    evaluation_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    num_train_epochs=3,
    weight_decay=0.01,
)

# Initialize Trainer
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_datasets['train'],
    eval_dataset=tokenized_datasets['validation'],
)

# Train the model
trainer.train()

# Evaluate the model
results = trainer.evaluate()
print(results)


/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(
Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


ValueError: Target modules {'distilbert.transformer.layer.*.attention.k_lin', 'distilbert.transformer.layer.*.attention.v_lin', 'distilbert.transformer.layer.*.attention.out_lin', 'distilbert.transformer.layer.*.attention.q_lin'} not found in the base model. Please check the target modules and try again.

In [10]:
pip install torch torchvision torchaudio


[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [11]:
import torch

# Check if PyTorch can use M1 GPU (if available)
device = "mps" if torch.backends.mps.is_available() else "cpu"
print(f"PyTorch is using device: {device}")

# Test a simple tensor operation
x = torch.rand(5, 3)
print(x)


PyTorch is using device: mps
tensor([[0.3478, 0.4213, 0.4079],
        [0.7827, 0.1973, 0.3392],
        [0.7093, 0.7479, 0.7710],
        [0.9388, 0.7181, 0.5494],
        [0.2890, 0.0617, 0.2387]])


In [12]:
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset

# Define a simple feedforward neural network
class SimpleNN(nn.Module):
    def __init__(self):
        super(SimpleNN, self).__init__()
        self.fc1 = nn.Linear(10, 50)
        self.fc2 = nn.Linear(50, 1)

    def forward(self, x):
        x = torch.relu(self.fc1(x))
        x = self.fc2(x)
        return x

# Create a dataset and dataloader
x_train = torch.rand(100, 10)
y_train = torch.rand(100, 1)
train_dataset = TensorDataset(x_train, y_train)
train_loader = DataLoader(train_dataset, batch_size=10, shuffle=True)

# Initialize the model, loss function, and optimizer
model = SimpleNN().to(device)
criterion = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), lr=0.01)

# Train the model
for epoch in range(5):
    for inputs, targets in train_loader:
        inputs, targets = inputs.to(device), targets.to(device)
        
        # Forward pass
        outputs = model(inputs)
        loss = criterion(outputs, targets)
        
        # Backward pass and optimization
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
    
    print(f"Epoch [{epoch+1}/5], Loss: {loss.item():.4f}")

print("Training complete!")


Epoch [1/5], Loss: 0.0326
Epoch [2/5], Loss: 0.0994
Epoch [3/5], Loss: 0.0864
Epoch [4/5], Loss: 0.1067
Epoch [5/5], Loss: 0.0656
Training complete!


In [13]:
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset
from peft import LoraConfig, get_peft_model

# Define a simple feedforward neural network
class SimpleNN(nn.Module):
    def __init__(self):
        super(SimpleNN, self).__init__()
        self.fc1 = nn.Linear(10, 50)
        self.fc2 = nn.Linear(50, 1)

    def forward(self, x):
        x = torch.relu(self.fc1(x))
        x = self.fc2(x)
        return x

# Instantiate the model and print its structure
model = SimpleNN()
print(model)


SimpleNN(
  (fc1): Linear(in_features=10, out_features=50, bias=True)
  (fc2): Linear(in_features=50, out_features=1, bias=True)
)


In [14]:
from peft import LoraConfig, get_peft_model

# Define LoRA configuration
lora_config = LoraConfig(
    r=4,  # Rank of the low-rank matrices
    lora_alpha=16,  # Scaling factor
    lora_dropout=0.1,  # Dropout rate
    target_modules=["fc1", "fc2"],  # Target modules for LoRA
)

# Wrap the model with LoRA
model = get_peft_model(model, lora_config)
print(model)


PeftModel(
  (base_model): LoraModel(
    (model): SimpleNN(
      (fc1): lora.Linear(
        (base_layer): Linear(in_features=10, out_features=50, bias=True)
        (lora_dropout): ModuleDict(
          (default): Dropout(p=0.1, inplace=False)
        )
        (lora_A): ModuleDict(
          (default): Linear(in_features=10, out_features=4, bias=False)
        )
        (lora_B): ModuleDict(
          (default): Linear(in_features=4, out_features=50, bias=False)
        )
        (lora_embedding_A): ParameterDict()
        (lora_embedding_B): ParameterDict()
        (lora_magnitude_vector): ModuleDict()
      )
      (fc2): lora.Linear(
        (base_layer): Linear(in_features=50, out_features=1, bias=True)
        (lora_dropout): ModuleDict(
          (default): Dropout(p=0.1, inplace=False)
        )
        (lora_A): ModuleDict(
          (default): Linear(in_features=50, out_features=4, bias=False)
        )
        (lora_B): ModuleDict(
          (default): Linear(in_features=

In [15]:
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset

# Create a dataset and dataloader
x_train = torch.rand(100, 10)
y_train = torch.rand(100, 1)
train_dataset = TensorDataset(x_train, y_train)
train_loader = DataLoader(train_dataset, batch_size=10, shuffle=True)

# Initialize the model, loss function, and optimizer
device = "mps" if torch.backends.mps.is_available() else "cpu"
model = model.to(device)
criterion = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), lr=0.01)

# Train the model
for epoch in range(5):
    for inputs, targets in train_loader:
        inputs, targets = inputs.to(device), targets.to(device)
        
        # Forward pass
        outputs = model(inputs)
        loss = criterion(outputs, targets)
        
        # Backward pass and optimization
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
    
    print(f"Epoch [{epoch+1}/5], Loss: {loss.item():.4f}")

print("Training complete!")


Epoch [1/5], Loss: 0.1123
Epoch [2/5], Loss: 0.1207
Epoch [3/5], Loss: 0.0828
Epoch [4/5], Loss: 0.0701
Epoch [5/5], Loss: 0.0580
Training complete!
